name: deploy_to_firebase_hosting

on:
  pull_request:
    types: [opened, closed]
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test
        env:
          SKIP_PREFLIGHT_CHECK: ${{ secrets.SKIP_PREFLIGHT_CHECK }}
      - name: Report coverage
        run: npm run coveralls
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: build
        run: npm run build
        env:
          SKIP_PREFLIGHT_CHECK: ${{ secrets.SKIP_PREFLIGHT_CHECK }}
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
